### PR TITLE
Adds MoneyCoach

### PR DESCRIPTION
**Pull request by Perjan**

### CODE REVIEW

**Comment by lewis-smith** [comment]
Hey Perjan, thanks for the PR :)

I couldn't get the interactive widget to load, is there any extra setup I need to do? https://cln.sh/0qfMy4Py

**Comment by Perjan** [comment]
A phone restart should reload all widgets again. 
Did you configure the widget before opening the app?

Thanks,
Perjan

**Comment by lewis-smith** [comment]
I have been thru the intro wizard. I removed the widget, rebooted my phone and then added it again but I still see the same thing :|

**Comment by Perjan** [comment]
> I have been thru the intro wizard. I removed the widget, rebooted my phone and then added it again but I still see the same thing :|

I uploaded a new version today, build 904. Please update the app and let me know.
Now it should work.

Thanks Lewis for spotting this huge bug.

**Comment by lewis-smith** [comment]
TBH it still doesn't work for me, but I'm merging as it seems quite buggy on Apple's side

**Pull request merged**
